// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecureP.Data;

#nullable disable

namespace SecureP.Data.Migrations
{
    [DbContext(typeof(AppDbContext<string>))]
    [Migration("20250416055241_Change_Parking_Rate_Table_Add_Concurrency_Check_To_ConcurrencyStamp")]
    partial class Change_Parking_Rate_Table_Add_Concurrency_Check_To_ConcurrencyStamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Identity")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecureP.Identity.Models.AppRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", "Identity");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClaimValue")
                        .HasColumnType("int");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "Identity");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUser<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DayOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", "Identity");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "Identity");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUserLicensePlate<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LicensePlateNumber")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "LicensePlateNumber");

                    b.ToTable("UserLicensePlates", "Identity");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "Identity");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUserParkingSubscription<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("ChangeSignageFee")
                        .HasColumnType("float");

                    b.Property<double>("ClampingFee")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParkingLocationRateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParkingZoneId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("SubscriptionFee")
                        .HasColumnType("float");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLocationRateId");

                    b.HasIndex("ParkingZoneId");

                    b.HasIndex("UserId");

                    b.ToTable("UserParkingSubscriptions", "Identity");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "Identity");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "Identity");
                });

            modelBuilder.Entity("SecureP.Identity.Models.ParkingLocation<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("ParkingLocations", "Identity");
                });

            modelBuilder.Entity("SecureP.Identity.Models.ParkingLocationRate<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParkingLocationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ParkingRateId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParkingRateId");

                    b.HasIndex("ParkingLocationId", "ParkingRateId", "EffectiveFrom")
                        .IsUnique()
                        .HasFilter("[ParkingLocationId] IS NOT NULL AND [ParkingRateId] IS NOT NULL");

                    b.ToTable("ParkingLocationRates", "Identity");
                });

            modelBuilder.Entity("SecureP.Identity.Models.ParkingRate<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DailyRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<double>("HourlyRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<double>("MonthlyRate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.HasKey("Id");

                    b.ToTable("ParkingRates", "Identity");
                });

            modelBuilder.Entity("SecureP.Identity.Models.ParkingZone<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AvailableSpaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ParkingLocationId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParkingLocationId");

                    b.ToTable("ParkingZones", "Identity");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppRoleClaim<string>", b =>
                {
                    b.HasOne("SecureP.Identity.Models.AppRole<string>", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUserClaim<string>", b =>
                {
                    b.HasOne("SecureP.Identity.Models.AppUser<string>", "User")
                        .WithMany("UserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUserLicensePlate<string>", b =>
                {
                    b.HasOne("SecureP.Identity.Models.AppUser<string>", "User")
                        .WithMany("UserLicensePlates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUserLogin<string>", b =>
                {
                    b.HasOne("SecureP.Identity.Models.AppUser<string>", "User")
                        .WithMany("UserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUserParkingSubscription<string>", b =>
                {
                    b.HasOne("SecureP.Identity.Models.ParkingLocationRate<string>", "ParkingLocationRate")
                        .WithMany("UserParkingSubscriptions")
                        .HasForeignKey("ParkingLocationRateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SecureP.Identity.Models.ParkingZone<string>", "ParkingZone")
                        .WithMany("UserParkingSubscriptions")
                        .HasForeignKey("ParkingZoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SecureP.Identity.Models.AppUser<string>", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ParkingLocationRate");

                    b.Navigation("ParkingZone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUserRole<string>", b =>
                {
                    b.HasOne("SecureP.Identity.Models.AppRole<string>", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureP.Identity.Models.AppUser<string>", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUserToken<string>", b =>
                {
                    b.HasOne("SecureP.Identity.Models.AppUser<string>", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureP.Identity.Models.ParkingLocationRate<string>", b =>
                {
                    b.HasOne("SecureP.Identity.Models.ParkingLocation<string>", "ParkingLocation")
                        .WithMany("ParkingLocationRates")
                        .HasForeignKey("ParkingLocationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SecureP.Identity.Models.ParkingRate<string>", "ParkingRate")
                        .WithMany("ParkingLocationRates")
                        .HasForeignKey("ParkingRateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParkingLocation");

                    b.Navigation("ParkingRate");
                });

            modelBuilder.Entity("SecureP.Identity.Models.ParkingZone<string>", b =>
                {
                    b.HasOne("SecureP.Identity.Models.ParkingLocation<string>", "ParkingLocation")
                        .WithMany("ParkingZones")
                        .HasForeignKey("ParkingLocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParkingLocation");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppRole<string>", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SecureP.Identity.Models.AppUser<string>", b =>
                {
                    b.Navigation("UserClaims");

                    b.Navigation("UserLicensePlates");

                    b.Navigation("UserLogins");

                    b.Navigation("UserRoles");

                    b.Navigation("UserTokens");
                });

            modelBuilder.Entity("SecureP.Identity.Models.ParkingLocation<string>", b =>
                {
                    b.Navigation("ParkingLocationRates");

                    b.Navigation("ParkingZones");
                });

            modelBuilder.Entity("SecureP.Identity.Models.ParkingLocationRate<string>", b =>
                {
                    b.Navigation("UserParkingSubscriptions");
                });

            modelBuilder.Entity("SecureP.Identity.Models.ParkingRate<string>", b =>
                {
                    b.Navigation("ParkingLocationRates");
                });

            modelBuilder.Entity("SecureP.Identity.Models.ParkingZone<string>", b =>
                {
                    b.Navigation("UserParkingSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
